### ISSUE TITLE
Citazione stampe Atlas

### ISSUE THREAD

**Issue by pigreco** [pigreco/COVID-19_ITA#4]
È auspicabile scrivere in tutte le stampe realizzate con QGIS:

`Realizzato con QGIS`

oppure, in questo caso specifico, `Realizzato con QGIS e Data Plotly` come da screenshot:

![image](https://user-images.githubusercontent.com/7631137/76680783-f461ee00-65eb-11ea-8a83-c7944b41455a.png)

**Comment by ghtmtt** [comment]
DataPlotly senza spazio ;)

**Comment by pigreco** [comment]
> DataPlotly senza spazio ;)

![image](https://user-images.githubusercontent.com/7631137/76680837-ab5e6980-65ec-11ea-9215-1206db8cb7ca.png)

fatto.

**Comment by pigreco** [comment]
Aggiungo DataPlotly 3.5 anche qui:

![image](https://user-images.githubusercontent.com/7631137/76681135-f928a100-65ef-11ea-897c-e6e4179864b8.png)
